// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tree_forward
int tree_forward(double task_max, int JM, double nu, double S);
RcppExport SEXP _TreeForward_tree_forward(SEXP task_maxSEXP, SEXP JMSEXP, SEXP nuSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type task_max(task_maxSEXP);
    Rcpp::traits::input_parameter< int >::type JM(JMSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_forward(task_max, JM, nu, S));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TreeForward_tree_forward", (DL_FUNC) &_TreeForward_tree_forward, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TreeForward(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
